# fly.toml app configuration file
app = 'notification-server-shy-sun-1340'
primary_region = 'cdg'

[build]
  command = "npm run build"

[env]
  NODE_ENV = "production"

[processes]
  app = "npm start"

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
